[package]
name = "utils"
version = "0.1.0"
authors = ["Aleksandar Pavlovic <aleksandar.pavlovic78@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]